resolver: lts-12.5
packages:
- '.'
- location:
    git: https://github.com/fendor/elm-bridge.git
    commit: 78f3c81b01551e6845256843f2571538db1718b7
  extra-dep: true

extra-deps: []

nix:
        packages: [ zlib, gmp ]
